### PR TITLE
Proofreading first 2 lessons

### PR DESCRIPTION
**Pull request by qjcg**
I tried to focus on:
- clarity
- spelling
- limiting line length to 80 characters (following the [guidelines for contributing](https://github.com/lwasser/python-ecology/blob/master/CONTRIBUTING.md#formatting-of-the-material))

Feedback welcome!

### CODE REVIEW

**Comment by lwasser** [comment]
hey. this is great - thank you. Quick question before i merge. It looks like all of the lines were shortened including the paragraphs of text. i'm curious about that given at some point we'll render MD --> html and the width will be constrained by CSS. is this just how SWC and DC format MD files? and will it translate to HTML when rendered with Jekyll?

i'm just wondering how that part works. Thanks John!

**Comment by tracykteal** [comment]
The Markdown will render in HTML, basically just how it looks as Markdown. The line breaks won't show up. Sometimes it's nice to have the line breaks for diffs for just one line, but it's not required.

**Comment by lwasser** [comment]
Ahh ok cool. got it. good to know.
I'll merge this now. Tracy, do you want me to build this as a gh-pages branch too at some point so when we merge, you can have a site page like SWC does?

**Comment by tracykteal** [comment]
Yes, it would be good to have it in the gh-pages branch. Thanks!

**Comment by lwasser** [comment]
ok! I'll build that out after john's done with his edits!
Leah

**Pull request merged**
