### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by qjcg**
Typos and other minor fixes (mostly cherry-picked commits from @fmichonneau that I am belatedly merging).

### CODE REVIEW

**Comment by tracykteal** [comment]
Thanks for these. I think though this has all moved over to https://github.com/datacarpentry/python-ecology. It should be the same as this repo here. Could you submit this PR to the lessons now in the main repo?

**Comment by qjcg** [comment]
Perfect, [done](https://github.com/datacarpentry/python-ecology/pull/4)!

**Comment by lwasser** [comment]
sorry @qjcg ! i've been super busy with moving stuff and did a poor job communicating i had submitted a PR to DC! glad you pushed it that way! The edits are great. i have been noticing more and more types as i review things for our workshop this week. you're catching them all among other fixes! :)

**Comment by qjcg** [comment]
It's all good @lwasser! :)

**Pull request closed without merging**
